### ISSUE TITLE
liblwpx-paranoidagent-perl: in use strict mode: warning: Use of uninitialized value

### ISSUE THREAD

**Issue by gregoa** [csirtgadgets/LWPx-ParanoidAgent#18]
We have the following bug reported to the Debian package of
LWPx-ParanoidAgent (https://bugs.debian.org/824181):

It doesn't seem to be a bug in the packaging, so you may want to take
a look. Thanks!

The bug report also contains a patch which looks good at first glance. It
applies against the package in Debian (which contains a patch that is also
merged in upstream master: a92ed8f4).

------8<-----------8<-----------8<-----------8<-----------8<-----

```
Package: liblwpx-paranoidagent-perl
Version: 1.10-5
Severity: normal

Dear Maintainer,

we have a server which uses a perl script. This perl script is written by "use strict;"
I needed to implement LWPx::ParanoidAgent into the script.

Now I get this warning after executing userAgent->get($url)
Use of uninitialized value $n in numeric eq (==) at /usr/share/perl5/LWPx/Protocol/http_paranoid.pm line 367.

This currently breaks the server because we are using STDIN/OUT/ERR and so on for communicating with the perl script.
This should be an easy fix.

Thank you.

-- System Information:
Debian Release: 8.4
  APT prefers stable-updates
  APT policy: (500, 'stable-updates'), (500, 'stable')
Architecture: amd64 (x86_64)

Kernel: Linux 3.16.0-4-amd64 (SMP w/4 CPU cores)
Locale: LANG=de_DE.UTF-8, LC_CTYPE=de_DE.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)

Versions of packages liblwpx-paranoidagent-perl depends on:
ii  ca-certificates       20141019+deb8u1
ii  libcrypt-ssleay-perl  0.58-1+b2
ii  libnet-dns-perl       0.81-2
ii  libwww-perl           6.08-1
ii  perl                  5.20.2-3+deb8u4

liblwpx-paranoidagent-perl recommends no packages.

liblwpx-paranoidagent-perl suggests no packages.

-- no debconf information


```
------8<-----------8<-----------8<-----------8<-----------8<-----

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by wesyoung** [comment]
ack, am looking into. i wasn't getting notifications for these; sorry about the delay..

**Comment by gregoa** [comment]
On Thu, 29 Sep 2016 04:14:38 -0700, Wes wrote:

> ack, am looking into. i wasn't getting notifications for these; sorry about the delay..

No worries, thanks for fixing the issue!

BTW, the .metadata directory and the .project file in the CPAN
tarball look like a mistake.

Cheers,
gregor

-- 
 .''`.  Homepage https://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer -  https://www.debian.org/
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-   NP: U2: Gone (New Mix)

**Comment by wesyoung** [comment]
gdi.
